sudo: false
language: python
cache: pip
python:
  - 2.6
  - 2.7
install:
  - pip install -r requirements.txt
  - pip install -r requirements_test.txt
before_script:
  - if [[ $TRAVIS_PYTHON_VERSION != 2.6 ]]; then flake8; fi
script:
  - py.test tests